-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        persistent_warps = true,
    },
    decoration = {
        shadow = {
            enabled = false,
        },
    },
    ecosystem = {
        no_donation_nag = true,
        no_update_news = true,
    },
    general = {
        allow_tearing = true,
        border_size = 0,
        gaps_in = 4,
        layout = "scrolling",
        snap = {
            enabled = true,
            respect_gaps = true,
        },
    },
    misc = {
        vrr = 1,
    },
    scrolling = {
        focus_fit_method = 1,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = false,
})
