-- Treesitter — syntax highlighting and parsing
return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "lua",
      "vim",
      "vimdoc",
      "query",
      "python",
      "rust",
      "go",
      "javascript",
      "typescript",
      "html",
      "css",
      "json",
      "yaml",
      "toml",
      "bash",
      "markdown",
      "markdown_inline",
      "c",
      "cpp",
      "java",
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
