[Appearance]
style=Fusion
color_scheme_path=~/.config/qt6ct/colors/gruvbox-dark.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
font="JetBrainsMono Nerd Font,11,-1,5,50,0,0,0,0,0"

[Fonts]
fixed="JetBrainsMono Nerd Font,11,-1,5,50,0,0,0,0,0"
general="JetBrainsMono Nerd Font,11,-1,5,50,0,0,0,0,0"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=0
double_click_interval=400
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=
toolbutton_style=4
underline_shortcut=false
wheel_scroll_lines=3

[PaletteEditor]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x2\x6a\0\0\x3\x16\0\0\x3\xf\0\0\x2\xb4\0\0\x2\x6a\0\0\x3\x16\0\0\x3\xf\0\0\x2\xb4\0\0\0\0\0\0)

[Palettes]
gruvbox-dark
