-- Noctalia Catppuccin Mocha Colors for Hyprland
-- Converted from noctalia-colors.conf for Lua config compatibility

background        = "rgba(1e1e2eff)"
base              = "rgba(1e1e2eff)"
text              = "rgba(cdd6f4ff)"
alternate_base    = "rgba(313244ff)"
bright_text       = "rgba(1e1e2eff)"
accent            = "rgba(b4befeff)"
accent_secondary  = "rgba(cba6f7ff)"

-- Full Catppuccin Mocha palette
base_color        = "rgba(1e1e2eff)"
crust             = "rgba(11111bff)"
mantle            = "rgba(181825ff)"
surface0          = "rgba(313244ff)"
surface1          = "rgba(45475aff)"
surface2          = "rgba(585b70ff)"
overlay0          = "rgba(6c7086ff)"
overlay1          = "rgba(7f849cff)"
text_color        = "rgba(cdd6f4ff)"
subtext1          = "rgba(bac2deff)"
subtext0          = "rgba(a6adc8ff)"
mauve             = "rgba(cba6f7ff)"
blue              = "rgba(89b4faff)"
lavender          = "rgba(b4befeff)"
green             = "rgba(a6e3a1ff)"
yellow            = "rgba(f9e2afff)"
peach             = "rgba(fab387ff)"
red               = "rgba(f38ba8ff)"
teal              = "rgba(94e2d5ff)"
sky               = "rgba(89dcebff)"
pink              = "rgba(f5c2e7ff)"
maroon            = "rgba(eba0acff)"
rosewater         = "rgba(f5e0dcff)"
flamingo          = "rgba(f2cdcdff)"

-- Border-specific aliases
col_group_border_active   = "rgba(b4befeff)"
col_group_border_inactive = "rgba(313244ff)"
