# Starship Prompt — Minimal Catppuccin Mocha
format = """\
$directory\
$git_branch\
$git_status\
$line_break\
$character\
"""

[directory]
style = "fg:#bac2de"
truncation_length = 2
truncation_symbol = "…/"

[git_branch]
style = "fg:#89b4fa"
format = " on [$symbol$branch]($style)"

[git_status]
style = "fg:#bac2de"
format = '[$all_status$ahead_behind]($style)'
conflicted = " 🏳"
up_to_date = ""
untracked = " ?"
stashed = " 📦"
modified = " !"
staged = " +"
renamed = " »"
deleted = " ✘"

[character]
success_symbol = "[❯](bold fg:#b4befe)"
error_symbol = "[❯](bold fg:#f38ba8)"
vicmd_symbol = "[❮](bold fg:#89b4fa)"
